### PR TITLE
Update config.py

### PR DESCRIPTION
**Pull request by Cyril9227**
Fixed a mistake : block.identity_skip instead of block.id_skip 

Updated get_default_block_list() to use serialized block args

### CODE REVIEW

**Comment by titu1994** [comment]
Thank you for the fix. May I ask why the block args have been replaced by parsing the args ? They are equivalent, otherwise model weights would not be loaded.

**Comment by Cyril9227** [comment]
Thank you for your quick feedback.

It is strictly equivalent as you said but now it makes use of the code you already wrote so it might be more coherent with your file and it also might be easier for a newcomer to understand how to use this code to serialize the args.

**Comment by titu1994** [comment]
While valid, I manually wrote the args as an example for extension. In cases like Mixnets where there are too many parameters it makes sense to use the string encoding directly but not for this one. 

If you would revert this edit, I'll merge the commit asap.

**Comment by Cyril9227** [comment]
Sure, edit should be reverted now

**Comment by titu1994** [comment]
Thank you for the fix !

**Pull request merged**
